### ISSUE TITLE
It's can't find me

### ISSUE THREAD

**Issue by morg00** [8C/SkypeSearch#1]

**Comment by morg00** [comment]
I search my second user. It's didn't search them

**Comment by 8C** [comment]
> I search my second user. It's didn't search them

Hi, can you please provide a screenshot of the error message it shows (if any)

The program fetches search results directly from the Skype API so if your skype account isn't showing up when you search it in this program, it probably also does not show up when you search it on Skype itself.

**Comment by morg00** [comment]
This is the result of the program
![Снимок экрана 2022-05-10 115114](https://user-images.githubusercontent.com/95364325/167589351-305c0d3d-df04-4cdb-a5ec-1fde0d245542.png)
Skype search

![Снимок экрана 2022-05-10 115340](https://user-images.githubusercontent.com/95364325/167589707-9d9154bf-950b-48f4-87d0-c9dd8a129ad4.png)

**Comment by morg00** [comment]
What do you think about this?

**Comment by 8C** [comment]
test

**Comment by 8C** [comment]
Confirm your email address

Your confirmation code is below — enter it in your open browser window and we'll help you get signed in.

YV4-3RX

If you didn’t request this email, there’s nothing to worry about — you can safely ignore it.

**Comment by 8C** [comment]
Welcome to Slack

Ta-da! You’ve joined your first Slack workspace and we couldn’t be more delighted. Here are your account details, along with some tips to help you get started.

Workspace name: hacked github

H

hackedgithub.slack.com []

Open Slack [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/messages/C02LZPRG5G8]
Tips for getting started

Take a quick tour

Get familiar with the basics of Slack [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/resources/using-slack/your-quick-start-guide-to-slack?utm_medium=email&utm_source=confirmation-new-join] so you’re ready to get to work in no time.

Start working in channels

Keep conversations organized in channels [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/features/channels?utm_medium=email&utm_source=confirmation-new-join] — organized spaces for everything related to a project, topic, or team.

Download Slack

For the best experience with Slack, download our apps [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/downloads?utm_medium=email&utm_source=confirmation-new-join&t=T02LA3LCG7L] for desktop and mobile.

See more tips [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-join]

If you have any questions as you’re getting started, drop us a note at ***@***.*** We’re glad you’re here!

**Comment by morg00** [comment]
> Добро пожаловать в Slack Ta-da! Вы присоединились к своему первому рабочему пространству Slack, и мы очень рады. Вот данные вашей учетной записи, а также несколько советов, которые помогут вам начать работу. Имя рабочей области: hacked github H hackedgithub.slack.com [] Open Slack [ https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/messages/C02LZPRG5G8 ] Советы по началу работы Краткий обзор Ознакомьтесь с основы [Slack](https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/resources/using-slack/your-quick-start-guide-to-slack?utm_medium=email&utm_source=confirmation-new-join) _ так что вы готовы приступить к работе в кратчайшие сроки. Начать работу в каналах Упорядочивать беседы по каналам [https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/features/channels?utm_medium=email&utm_source=confirmation-new-join ] — организованные пространства для всего, что связано с проектом, темой или командой. Загрузите Slack Чтобы получить наилучшие впечатления от Slack, загрузите наши приложения [ https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/downloads?utm_medium=email&utm_source=confirmation-new-join&t=T02LA3LCG7L ] для настольных и мобильных устройств. [См. дополнительные](https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-join) советы [new-join](https://hackedgithub.slack.com/x-p2690122424258-3532651319312-3511254355044/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-join) ] Если у вас возникнут какие-либо вопросы, напишите нам по адресу ***@***.*** Мы рады, что вы здесь!

Sorry, I don't have an @reply.github.com email address. Can you send me an invitation?

**Comment by 8C** [comment]
> What do you think about this?

ignore the email that was sent here (that i deleted), was just doing some pen-testing haha

**Comment by morg00** [comment]
Can I get there somehow?

**Comment by morg00** [comment]
When I saw this, I was very happy. Now I'm upset.((( haha

**Comment by 8C** [comment]
> When I saw this, I was very happy. Now I'm upset.((( haha

haha it's secret 😅

**Comment by morg00** [comment]
Give to him who asks of you, and do not turn away from him who wants to borrow from you

Source: https://bible.knowing-jesus.com/Matthew/5/42
haha

**Comment by morg00** [comment]
Mail for secrets: komowaw712@3dmasti.com

**Comment by 8C** [comment]
x_x

**Comment by 8C** [comment]
gjdhgk

**Comment by morg00** [comment]
.
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠈⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠄⢰⡆⠄⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⡿⢿⣿⣿⣿
⣿⣿⡿⠃⠄⠉⠛⠛⠛⠛⠃⠸⠇⠘⠛⠛⠛⠛⠉⠄⠘⢿⣿⣿
⣿⣦⣄⠄⠛⠛⠛⠛⠛⠛⠛⢄⡠⠙⠛⠛⠛⠛⠛⠛⠄⣠⣴⣿
⣿⣿⣿⣆⣠⣶⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣶⣄⣰⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⢸⡇⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠄⠘⠃⠄⠙⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⡄⢠⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

**Comment by morg00** [comment]
> gjdhgk

what does it mean?
