### ISSUE TITLE
What do you think about this?

### ISSUE THREAD

**Issue by morg00** [8C/SkypeSearch#2]
This is the result of the program
![Снимок экрана 2022-05-10 115114](https://user-images.githubusercontent.com/95364325/167589351-305c0d3d-df04-4cdb-a5ec-1fde0d245542.png)
Skype search

![Снимок экрана 2022-05-10 115340](https://user-images.githubusercontent.com/95364325/167589707-9d9154bf-950b-48f4-87d0-c9dd8a129ad4.png)

**Comment by 8C** [comment]
![image](https://user-images.githubusercontent.com/6260045/167598050-d6819bdc-605a-4a5b-b422-50163aad70e1.png)

This is not an issue with the application. You have your search discovery settings disabled, hence why your skype profile doesn't show up when normally searched on Skype too.

You can change your Skype discoverability settings at: https://secure.skype.com/portal/profile

Closing this.
